name: Tests

on:
  push:
    branches: [master]
  pull_request:
    branches: "*"

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: ["3.2", "3.3", "3.4", "4.0"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler: default
          bundler-cache: true

      - name: StandardRb check
        run: bundle exec standardrb

      - name: Run tests
        run: bundle exec rake test

      - name: Upload coverage
        if: matrix.ruby == '3.4'
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage/.resultset.json
